# -*- coding: utf-8 -*-
"""config.json.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihoTsMEJWaTOaS8pHYX2DOVUoMTnIyqg
"""

{
  "cleaning": {
    "duplicate_policy": "upsert",
    "required_fields": [
      "source",
      "collection_method",
      "category",
      "title",
      "url",
      "collected_at"
    ],
    "remove_tracking_params": true
  }
}