# -*- coding: utf-8 -*-
"""test_cleaning.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihoTsMEJWaTOaS8pHYX2DOVUoMTnIyqg
"""

import unittest
from main import (
    choose_better_content,
    empty_to_none,
    normalize_text,
    normalize_url,
    parse_date,
    validate_required_fields,
)


class TestDataCleaning(unittest.TestCase):
    def test_normalize_text(self):
        html_input = "<p>AI 뉴스 기사&nbsp;본문입니다.</p><br>무단전재 및 재배포 금지"
        cleaned = normalize_text(html_input)
        self.assertEqual(cleaned, "AI 뉴스 기사 본문입니다.")

    def test_normalize_url(self):
        dirty_url = "https://news.example.com/tech/?utm_source=twitter&fbclid=abc123#article"
        canonical = normalize_url(dirty_url, remove_tracking_params=True)
        self.assertEqual(canonical, "https://news.example.com/tech")

    def test_parse_date(self):
        parsed = parse_date("2026-08-24T10:00:00Z")
        self.assertIsNotNone(parsed)
        self.assertTrue("2026-08-24" in parsed)

    def test_empty_to_none(self):
        self.assertIsNone(empty_to_none("   "))
        self.assertEqual(empty_to_none("내용"), "내용")

    def test_choose_better_content(self):
        short_c = "짧은 본문"
        long_c = "더 길고 풍부한 크롤링 본문 내용입니다."
        self.assertEqual(choose_better_content(short_c, long_c), long_c)

    def test_validate_required_fields(self):
        row = {"source": "RSS", "title": "제목", "url": "https://example.com"}
        missing = validate_required_fields(row, ["source", "title", "url", "category"])
        self.assertIn("category", missing)


if __name__ == "__main__":
    unittest.main()